panier_ecommerce:
    resource: "@PanierEcommerceBundle/Resources/config/routing.yml"
    prefix:   /ecomm

#ecommerce:
    #resource: "@EcommerceBundle/Resources/config/routing.yml"
    #prefix:   /ecommerce

app:
    resource: '@AppBundle/Controller/'
    type: annotation

#connexion facebook, twitter
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /connect

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin

# app/config/routing.yml
facebook_login:
    path: /login/check-facebook

google_login:
    path: /login/check-google

custom_login:
    path: /login/check-custom

github_login:
    path: /login/check-github